(define (frame-outline frame)
  (let ((tl (make-vect 0 1))
	(tr (make-vect 1 1))
	(bl (make-vect 0 0))
	(br (make-vect 1 0)))
    (segments->painter (list (make-segment bl br)
			     (make-segment br tr)
			     (make-segment tr tl)
			     (make-segment tl bl)))))

(define (draw-x frame)
  (let ((tl (make-vect 0 1))
	(tr (make-vect 1 1))
	(bl (make-vect 0 0))
	(br (make-vect 1 0)))
    (segments->painter (list (make-segment bl tr)
			     (make-segment br tl)))))

(define (draw-diamond frame)
  (let ((b (make-vect 0.5 0))
	(r (make-vect 1 0.5))
	(t (make-vect 0.5 1))
	(l (make-vect 0 0.5)))
    (segments->painter (list (make-segment b r)
			     (make-segment r t)
			     (make-segment t l)
			     (make-segment l b)))))
